# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    menuCollection:
        -
            label: lint
            enabled: true
            icon: fas fa-spell-check
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::LINT
                action: yaml
            children:
                -
                    label: yaml
                    enabled: true
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::LINT
                        action: yaml
        -
            label: pdepend
            enabled: true
            icon: fas fa-box
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PDEPEND
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: true
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PDEPEND
                        action: dashboard
        -
            label: phpcodesniffer
            enabled: false
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PHPCODESNIFFER
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: false
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PHPCODESNIFFER
                        action: dashboard
        -
            label: phpcsfixer
            enabled: false
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PHPCSFIXER
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: false
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PHPCSFIXER
                        action: dashboard
        -
            label: phpcpd
            enabled: true
            icon: fas fa-clone
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PHPCPD
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: true
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PHPCPD
                        action: dashboard
        -
            label: phpdcd
            enabled: true
            icon: fas fa-skull
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PHPDCD
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: true
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PHPDCD
                        action: dashboard
        -
            label: phploc
            enabled: true
            icon: fas fa-sitemap
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PHPLOC
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: true
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PHPLOC
                        action: dashboard
        -
            label: phpmetric
            enabled: false
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PHPMETRIC
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: false
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PHPMETRIC
                        action: dashboard
        -
            label: phpmd
            enabled: true
            icon: fas fa-snowplow
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PHPMD
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: true
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PHPMD
                        action: dashboard
        -
            label: phpstan
            enabled: true
            icon: fas fa-cogs
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::PHPSTAN
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: true
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::PHPSTAN
                        action: dashboard
        -
            label: security
            enabled: true
            icon: fas fa-shield-alt
            route: default_action
            parameters:
                vendor: !php/const App\Domain\Vendors::SECURITY
                action: dashboard
            children:
                -
                    label: dashboard
                    enabled: true
                    route: default_action
                    parameters:
                        vendor: !php/const App\Domain\Vendors::SECURITY
                        action: dashboard

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $menuCollection: '%menuCollection%'
            $kernelProjectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    _instanceof:
        Symfony\Component\Serializer\SerializerAwareInterface:
            calls:
                - ['setSerializer', ['@serializer']]

    App\EventListener\MenuListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 4 }

    App\EventListener\ReportListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 2 }
